
# CDHはIPv6は未サポート
# CentOS7では非推奨となってるけど、CDHでは無効にする必要がある、って明記されてる
# https://www.cloudera.com/documentation/enterprise/release-notes/topics/rn_consolidated_pcm.html#cdh_cm_network_security
# http://community.cloudera.com/t5/Cloudera-Manager-Installation/Disabling-IPv6/m-p/51849
# 参考: https://github.com/juju4/ansible-ipv6/blob/master/tasks/ipv6-disable.yml

# CentOS7でのIPv6の無効化方法
# https://wiki.centos.org/FAQ/CentOS7#head-8984faf811faccca74c7bcdd74de7467f2fcd8ee

- name: CommentOut IPv6 row at /etc/hosts
  replace:
    dest: /etc/hosts
    regexp: '^::1'
    replace: '#::1'

- name: Disable IPv6 with sysctl
  sysctl: name={{ item }} value=1 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

# inetはipv4のみ
- name: ssh config AddressFamily to inet
  replace:
    dest: /etc/ssh/sshd_config
    regexp: '^#AddressFamily any'
    replace: 'AddressFamily inet'
  notify:
    - restart sshd
