
- name: restart ntp
  service:
     name=ntpd
     state=restarted
     enabled=yes

- name: restart iptables
  service:
     name=iptables
     state=restarted
     enabled=yes

- name: restart vsftpd
  service:
    name=vsftpd
    state=restarted
    enabled=yes

- name: start vsftpd
  service:
    name=vsftpd
    state=started
    enabled=yes

- name: disable firewalld
  service:
    name=firewalld
    state=stopped
    enabled=no
